spring:
  datasource:
    url: jdbc:hsqldb:file:hsqldb/db
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    username: sa 
    password: 
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
